version: "3.8"
services: 
  api:
    build: ./api_marhaba_app
    container_name: marhaba-web-app_api
    ports:
      - '8080:8080'
    volumes:
    
      - ./api_marhaba_app:/server
      - ./api_marhaba_app:/node_modules
  frontend:
    build: ./marhaba_app_front
    container_name: front_marhaba_c
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true